---
- name: Deploy Filebeat to Kubernetes
  hosts: local
  tasks:

    - name: Apply Filebeat ConfigMap
      command: kubectl apply -f ../k8s/filebeat-config.yaml
      register: config_output

    - debug:
        var: config_output.stdout

    - name: Apply Filebeat DaemonSet
      command: kubectl apply -f ../k8s/filebeat-daemonset.yaml
      register: daemonset_output

    - debug:
        var: daemonset_output.stdout
