input {
  beats {
    port => 5000
  }
}

filter {

  # Process ONLY backend service logs  
  if [k8s_container] == "backend" {

    # Parse FastAPI HTTP logs
    if [message] =~ "HTTP/1.1" {
      grok {
        match => {
          "message" => "%{IPORHOST:client_ip}:%{INT:client_port} - \"%{WORD:http_method} %{DATA:path} HTTP/%{NUMBER:http_version}\" %{INT:status_code} %{GREEDYDATA:http_status_text}"
        }
        remove_field => ["tags"]
      }
    }

    # Parse Chat Logs
    if [message] =~ "User asked" {
      grok {
        match => { "message" => "User asked: %{GREEDYDATA:user_query}" }
      }
    }

    # Supervisor Escalations
    if [message] =~ "Escalation" {
      mutate { add_field => { "event_type" => "escalation_triggered" } }
    }

    # Ollama REQUEST
    if [message] =~ "OLLAMA REQUEST" {
      grok {
        match => { "message" => "OLLAMA REQUEST prompt=\"%{GREEDYDATA:ollama_prompt}\"" }
      }
      mutate { add_field => { "event_type" => "ollama_request" } }
    }

    # Ollama RESPONSE
    if [message] =~ "OLLAMA RESPONSE" {
      grok {
        match => { "message" => "OLLAMA RESPONSE status=%{INT:ollama_status} duration=%{NUMBER:ollama_latency}ms" }
      }
      mutate { add_field => { "event_type" => "ollama_response" } }
    }

  } else {
    # Ignore other pod logs — prevents _grokparsefailure
    mutate {
      add_tag => ["skip_parse"]
    }
  }

}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "kubernetes-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}
